# This blueprint allows you to map actions to the different controls on an Aqara H2 Rotary Dial
#
# This automation is built for a device in EVENT mode rather than COMMAND mode. As there is some cross-over between the two modes, it is NOT recommended to use automations for both modes at the same time.

blueprint:
  name: Aqara H2 Rotary Dial - Remote (Event Mode)

  source_url: https://raw.githubusercontent.com/Morpheus90x/home-assistant/refs/heads/main/aqara_h2_rotary_dial_remote.yaml

  description: >-
    This automation allows using an Aqara H2 Rotary Dial (ZigBee) to trigger actions.

  domain: automation

  input:
    dial:
      name: Aqara H1 Rotary Dial
      description: Select the rotary dial you wish to use
      selector:
        device:
          integration: zha
          manufacturer: LUMI
          model: lumi.switch.agl011
    single:
      name: Single Press
      description: The action to perform on a single press of the dial button
      selector:
        action:
      default: []
    double:
      name: Double Press
      description: The action to perform on a double press of the dial button
      selector:
        action:
      default: []
    long:
      name: Long Press
      description: The action to perform on a long press of the dial button
      selector:
        action:
      default: []
    left:
      name: Left Turn
      description: The action to perform on rotating the dial to the left
      selector:
        action:
      default: []
    right:
      name: Right Turn
      description: The action to perform on rotating the dial to the right
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input dial

action:
  - choose:
      # Single press on the button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "1_single" }}'
        sequence: !input single

      # Double press on the button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "1_double" }}'
        sequence: !input double

      # Long press on the button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "1_hold" }}'
        sequence: !input long

      # Rotate dial to the left
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "stop_rotation" and trigger.event.data.args.rotation_direction == -1 }}'
        sequence: !input left

      # Rotate dial to the right
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "stop_rotation" and trigger.event.data.args.rotation_direction == 1 }}'
        sequence: !input right

    # Any other event will cancel the repeat loops.
    default: []
